json push
Error: Possible Unhandled Promise Rejection (id:19)
SyntaxError: JSON Parse error: Unrecognized token '<'
parse@[native code]

Potential reasons:
either post or get is positing or retrieving html instead of json

I think I read something about IOS natively not being able to post JSON or something